### ISSUE TITLE
MIT license for TSMP2

### ISSUE THREAD

**Issue by jjokella** [HPSCTerrSys/TSMP2#25]
Proposal: Adding an MIT license for TSMP2.

# Example

Please suggest additions/removals of names. 

I copied the names from TSMP1 and removed contributors I believed not to have been involved in TSMP2

Following style from https://github.com/parflow/parflow/ (`LICENSE.txt` and `CONTRIBUTORS.txt`)

## License file

https://github.com/HPSCTerrSys/TSMP2/blob/ed57160f9191a9b424217c494983963e566f0dc3/LICENSE.txt#L1-L21

## Contributors file
https://github.com/HPSCTerrSys/TSMP2/blob/ed57160f9191a9b424217c494983963e566f0dc3/CONTRIBUTORS.txt#L1-L13

**Comment by kvrigor** [comment]
I've completely overlooked TSMP2's lack of license 😅.... feel free to raise a PR!

**Comment by kgoergen** [comment]
Maybe do it similarly as it is done with ParFlow: "Copyright by the TSMP2 Team (see the CONTRIBUTORS.txt file)" in addition to LICENSE.txt. MIT license is certainly suitable.

**Comment by kgoergen** [comment]
I would put most important contributors to the front, I guess it is quite clear who spend most of the time with TSMP2, the others in alphabetical order.

**Comment by DCaviedesV** [comment]
Fully support the CONTRIBUTORS.txt file. This is also good practice because it is machine readable and helps indexing of software projects. Makes software more FAIR.

**Comment by jjokella** [comment]
Regarding the order of names in `CONTRIBUTIONS.md`: So far this should be more or less the order of the TSMP-license file. Exception: I put @kvrigor  in front as I think of @kvrigor as the main developer.

If this is ok with everyone, I will leave the order in the `CONTRIBUTORS.md` as is in the course of this issue/PR.

We could then open a follow-up issue discussing style/order of the `CONTRIBUTORS.md`. Or in more general terms: How to highlight various contributions with the goal of giving due credit.
